/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRelancesRouteImport } from './routes/_authenticated/relances'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentPlansRouteImport } from './routes/_authenticated/payment-plans'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDebtorsRouteImport } from './routes/_authenticated/debtors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminSystemConfigRouteImport } from './routes/_admin/system-config'
import { Route as AdminLogsRouteImport } from './routes/_admin/logs'
import { Route as AdminGlobalRelancesRouteImport } from './routes/_admin/global-relances'
import { Route as AdminGlobalDebtorsRouteImport } from './routes/_admin/global-debtors'
import { Route as AdminCommissionsRouteImport } from './routes/_admin/commissions'
import { Route as AdminClientsRouteImport } from './routes/_admin/clients'
import { Route as AdminClassificationsRouteImport } from './routes/_admin/classifications'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedDebtorsIndexRouteImport } from './routes/_authenticated/debtors.index'
import { Route as AuthenticatedInvoicesImportRouteImport } from './routes/_authenticated/invoices.import'
import { Route as AuthenticatedInvoicesArchiveRouteImport } from './routes/_authenticated/invoices.archive'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedDebtorsNewRouteImport } from './routes/_authenticated/debtors.new'
import { Route as AuthenticatedDebtorsDebtorIdRouteImport } from './routes/_authenticated/debtors.$debtorId'
import { Route as AdminSwitchClientIdRouteImport } from './routes/_admin/switch.$clientId'
import { Route as AuthenticatedRelancesPlanDebtorIdRouteImport } from './routes/_authenticated/relances.plan.$debtorId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelancesRoute = AuthenticatedRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentPlansRoute =
  AuthenticatedPaymentPlansRouteImport.update({
    id: '/payment-plans',
    path: '/payment-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebtorsRoute = AuthenticatedDebtorsRouteImport.update({
  id: '/debtors',
  path: '/debtors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminSystemConfigRoute = AdminSystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGlobalRelancesRoute = AdminGlobalRelancesRouteImport.update({
  id: '/global-relances',
  path: '/global-relances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGlobalDebtorsRoute = AdminGlobalDebtorsRouteImport.update({
  id: '/global-debtors',
  path: '/global-debtors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassificationsRoute = AdminClassificationsRouteImport.update({
  id: '/classifications',
  path: '/classifications',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedDebtorsIndexRoute =
  AuthenticatedDebtorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDebtorsRoute,
  } as any)
const AuthenticatedInvoicesImportRoute =
  AuthenticatedInvoicesImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesArchiveRoute =
  AuthenticatedInvoicesArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedDebtorsNewRoute = AuthenticatedDebtorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedDebtorsRoute,
} as any)
const AuthenticatedDebtorsDebtorIdRoute =
  AuthenticatedDebtorsDebtorIdRouteImport.update({
    id: '/$debtorId',
    path: '/$debtorId',
    getParentRoute: () => AuthenticatedDebtorsRoute,
  } as any)
const AdminSwitchClientIdRoute = AdminSwitchClientIdRouteImport.update({
  id: '/switch/$clientId',
  path: '/switch/$clientId',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedRelancesPlanDebtorIdRoute =
  AuthenticatedRelancesPlanDebtorIdRouteImport.update({
    id: '/plan/$debtorId',
    path: '/plan/$debtorId',
    getParentRoute: () => AuthenticatedRelancesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/cgu': typeof CguRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/classifications': typeof AdminClassificationsRoute
  '/clients': typeof AdminClientsRoute
  '/commissions': typeof AdminCommissionsRoute
  '/global-debtors': typeof AdminGlobalDebtorsRoute
  '/global-relances': typeof AdminGlobalRelancesRoute
  '/logs': typeof AdminLogsRoute
  '/system-config': typeof AdminSystemConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debtors': typeof AuthenticatedDebtorsRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/payment-plans': typeof AuthenticatedPaymentPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/relances': typeof AuthenticatedRelancesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/switch/$clientId': typeof AdminSwitchClientIdRoute
  '/debtors/$debtorId': typeof AuthenticatedDebtorsDebtorIdRoute
  '/debtors/new': typeof AuthenticatedDebtorsNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/archive': typeof AuthenticatedInvoicesArchiveRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/debtors/': typeof AuthenticatedDebtorsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/relances/plan/$debtorId': typeof AuthenticatedRelancesPlanDebtorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/cgu': typeof CguRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/classifications': typeof AdminClassificationsRoute
  '/clients': typeof AdminClientsRoute
  '/commissions': typeof AdminCommissionsRoute
  '/global-debtors': typeof AdminGlobalDebtorsRoute
  '/global-relances': typeof AdminGlobalRelancesRoute
  '/logs': typeof AdminLogsRoute
  '/system-config': typeof AdminSystemConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/payment-plans': typeof AuthenticatedPaymentPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/relances': typeof AuthenticatedRelancesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/switch/$clientId': typeof AdminSwitchClientIdRoute
  '/debtors/$debtorId': typeof AuthenticatedDebtorsDebtorIdRoute
  '/debtors/new': typeof AuthenticatedDebtorsNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/archive': typeof AuthenticatedInvoicesArchiveRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/debtors': typeof AuthenticatedDebtorsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/relances/plan/$debtorId': typeof AuthenticatedRelancesPlanDebtorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cgu': typeof CguRoute
  '/dpa': typeof DpaRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_admin/classifications': typeof AdminClassificationsRoute
  '/_admin/clients': typeof AdminClientsRoute
  '/_admin/commissions': typeof AdminCommissionsRoute
  '/_admin/global-debtors': typeof AdminGlobalDebtorsRoute
  '/_admin/global-relances': typeof AdminGlobalRelancesRoute
  '/_admin/logs': typeof AdminLogsRoute
  '/_admin/system-config': typeof AdminSystemConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debtors': typeof AuthenticatedDebtorsRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/payment-plans': typeof AuthenticatedPaymentPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/relances': typeof AuthenticatedRelancesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_admin/switch/$clientId': typeof AdminSwitchClientIdRoute
  '/_authenticated/debtors/$debtorId': typeof AuthenticatedDebtorsDebtorIdRoute
  '/_authenticated/debtors/new': typeof AuthenticatedDebtorsNewRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/archive': typeof AuthenticatedInvoicesArchiveRoute
  '/_authenticated/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/_authenticated/debtors/': typeof AuthenticatedDebtorsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/relances/plan/$debtorId': typeof AuthenticatedRelancesPlanDebtorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$404'
    | '/cgu'
    | '/dpa'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/classifications'
    | '/clients'
    | '/commissions'
    | '/global-debtors'
    | '/global-relances'
    | '/logs'
    | '/system-config'
    | '/dashboard'
    | '/debtors'
    | '/inbox'
    | '/invoices'
    | '/payment-plans'
    | '/profile'
    | '/relances'
    | '/settings'
    | '/switch/$clientId'
    | '/debtors/$debtorId'
    | '/debtors/new'
    | '/invoices/$invoiceId'
    | '/invoices/archive'
    | '/invoices/import'
    | '/debtors/'
    | '/invoices/'
    | '/relances/plan/$debtorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/cgu'
    | '/dpa'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/classifications'
    | '/clients'
    | '/commissions'
    | '/global-debtors'
    | '/global-relances'
    | '/logs'
    | '/system-config'
    | '/dashboard'
    | '/inbox'
    | '/payment-plans'
    | '/profile'
    | '/relances'
    | '/settings'
    | '/switch/$clientId'
    | '/debtors/$debtorId'
    | '/debtors/new'
    | '/invoices/$invoiceId'
    | '/invoices/archive'
    | '/invoices/import'
    | '/debtors'
    | '/invoices'
    | '/relances/plan/$debtorId'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/_admin'
    | '/_authenticated'
    | '/cgu'
    | '/dpa'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_admin/classifications'
    | '/_admin/clients'
    | '/_admin/commissions'
    | '/_admin/global-debtors'
    | '/_admin/global-relances'
    | '/_admin/logs'
    | '/_admin/system-config'
    | '/_authenticated/dashboard'
    | '/_authenticated/debtors'
    | '/_authenticated/inbox'
    | '/_authenticated/invoices'
    | '/_authenticated/payment-plans'
    | '/_authenticated/profile'
    | '/_authenticated/relances'
    | '/_authenticated/settings'
    | '/_admin/switch/$clientId'
    | '/_authenticated/debtors/$debtorId'
    | '/_authenticated/debtors/new'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/archive'
    | '/_authenticated/invoices/import'
    | '/_authenticated/debtors/'
    | '/_authenticated/invoices/'
    | '/_authenticated/relances/plan/$debtorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CguRoute: typeof CguRoute
  DpaRoute: typeof DpaRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relances': {
      id: '/_authenticated/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof AuthenticatedRelancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-plans': {
      id: '/_authenticated/payment-plans'
      path: '/payment-plans'
      fullPath: '/payment-plans'
      preLoaderRoute: typeof AuthenticatedPaymentPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debtors': {
      id: '/_authenticated/debtors'
      path: '/debtors'
      fullPath: '/debtors'
      preLoaderRoute: typeof AuthenticatedDebtorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/system-config': {
      id: '/_admin/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof AdminSystemConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/logs': {
      id: '/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/global-relances': {
      id: '/_admin/global-relances'
      path: '/global-relances'
      fullPath: '/global-relances'
      preLoaderRoute: typeof AdminGlobalRelancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/global-debtors': {
      id: '/_admin/global-debtors'
      path: '/global-debtors'
      fullPath: '/global-debtors'
      preLoaderRoute: typeof AdminGlobalDebtorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/commissions': {
      id: '/_admin/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clients': {
      id: '/_admin/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/classifications': {
      id: '/_admin/classifications'
      path: '/classifications'
      fullPath: '/classifications'
      preLoaderRoute: typeof AdminClassificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/debtors/': {
      id: '/_authenticated/debtors/'
      path: '/'
      fullPath: '/debtors/'
      preLoaderRoute: typeof AuthenticatedDebtorsIndexRouteImport
      parentRoute: typeof AuthenticatedDebtorsRoute
    }
    '/_authenticated/invoices/import': {
      id: '/_authenticated/invoices/import'
      path: '/import'
      fullPath: '/invoices/import'
      preLoaderRoute: typeof AuthenticatedInvoicesImportRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/archive': {
      id: '/_authenticated/invoices/archive'
      path: '/archive'
      fullPath: '/invoices/archive'
      preLoaderRoute: typeof AuthenticatedInvoicesArchiveRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/debtors/new': {
      id: '/_authenticated/debtors/new'
      path: '/new'
      fullPath: '/debtors/new'
      preLoaderRoute: typeof AuthenticatedDebtorsNewRouteImport
      parentRoute: typeof AuthenticatedDebtorsRoute
    }
    '/_authenticated/debtors/$debtorId': {
      id: '/_authenticated/debtors/$debtorId'
      path: '/$debtorId'
      fullPath: '/debtors/$debtorId'
      preLoaderRoute: typeof AuthenticatedDebtorsDebtorIdRouteImport
      parentRoute: typeof AuthenticatedDebtorsRoute
    }
    '/_admin/switch/$clientId': {
      id: '/_admin/switch/$clientId'
      path: '/switch/$clientId'
      fullPath: '/switch/$clientId'
      preLoaderRoute: typeof AdminSwitchClientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/relances/plan/$debtorId': {
      id: '/_authenticated/relances/plan/$debtorId'
      path: '/plan/$debtorId'
      fullPath: '/relances/plan/$debtorId'
      preLoaderRoute: typeof AuthenticatedRelancesPlanDebtorIdRouteImport
      parentRoute: typeof AuthenticatedRelancesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassificationsRoute: typeof AdminClassificationsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminGlobalDebtorsRoute: typeof AdminGlobalDebtorsRoute
  AdminGlobalRelancesRoute: typeof AdminGlobalRelancesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSystemConfigRoute: typeof AdminSystemConfigRoute
  AdminSwitchClientIdRoute: typeof AdminSwitchClientIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassificationsRoute: AdminClassificationsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminGlobalDebtorsRoute: AdminGlobalDebtorsRoute,
  AdminGlobalRelancesRoute: AdminGlobalRelancesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSystemConfigRoute: AdminSystemConfigRoute,
  AdminSwitchClientIdRoute: AdminSwitchClientIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDebtorsRouteChildren {
  AuthenticatedDebtorsDebtorIdRoute: typeof AuthenticatedDebtorsDebtorIdRoute
  AuthenticatedDebtorsNewRoute: typeof AuthenticatedDebtorsNewRoute
  AuthenticatedDebtorsIndexRoute: typeof AuthenticatedDebtorsIndexRoute
}

const AuthenticatedDebtorsRouteChildren: AuthenticatedDebtorsRouteChildren = {
  AuthenticatedDebtorsDebtorIdRoute: AuthenticatedDebtorsDebtorIdRoute,
  AuthenticatedDebtorsNewRoute: AuthenticatedDebtorsNewRoute,
  AuthenticatedDebtorsIndexRoute: AuthenticatedDebtorsIndexRoute,
}

const AuthenticatedDebtorsRouteWithChildren =
  AuthenticatedDebtorsRoute._addFileChildren(AuthenticatedDebtorsRouteChildren)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesArchiveRoute: typeof AuthenticatedInvoicesArchiveRoute
  AuthenticatedInvoicesImportRoute: typeof AuthenticatedInvoicesImportRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesArchiveRoute: AuthenticatedInvoicesArchiveRoute,
  AuthenticatedInvoicesImportRoute: AuthenticatedInvoicesImportRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedRelancesRouteChildren {
  AuthenticatedRelancesPlanDebtorIdRoute: typeof AuthenticatedRelancesPlanDebtorIdRoute
}

const AuthenticatedRelancesRouteChildren: AuthenticatedRelancesRouteChildren = {
  AuthenticatedRelancesPlanDebtorIdRoute:
    AuthenticatedRelancesPlanDebtorIdRoute,
}

const AuthenticatedRelancesRouteWithChildren =
  AuthenticatedRelancesRoute._addFileChildren(
    AuthenticatedRelancesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtorsRoute: typeof AuthenticatedDebtorsRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPaymentPlansRoute: typeof AuthenticatedPaymentPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRelancesRoute: typeof AuthenticatedRelancesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtorsRoute: AuthenticatedDebtorsRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPaymentPlansRoute: AuthenticatedPaymentPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRelancesRoute: AuthenticatedRelancesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CguRoute: CguRoute,
  DpaRoute: DpaRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
